name: tokopedia_clone_ui
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=3.3.1 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.6
    collection: ^1.18.0
    keyboard_dismisser: ^3.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/icons/
        - assets/images/

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    fonts:
        - family: OpenSouceOne
          fonts:
              - asset: assets/fonts/OpenSauceOne-Bold.ttf
                weight: 700
              - asset: assets/fonts/OpenSauceOne-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/OpenSauceOne-Medium.ttf
                weight: 500
              - asset: assets/fonts/OpenSauceOne-Regular.ttf
                weight: 400
              - asset: assets/fonts/OpenSauceOne-Light.ttf
                weight: 300

    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
